x_arm:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  position_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - shoulder_pan_joint
      - shoulder_pitch_joint
      - elbow_roll_joint
      - elbow_pitch_joint
      - wrist_roll_joint
      - wrist_pitch_joint
      - gripper_roll_joint


  gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - finger_joint1
      - finger_joint2